micronaut:
  application:
    name: snapswapMockApi
  server:
    port: 8089
    ssl:
      enabled: true
      key-store:
        path: classpath:server.p12
        password: wallee2023
        type: PKCS12
#      buildSelfSigned: true
netty:
  default:
    allocator:
      max-order: 3
