package com.oonyy.model.internal

import com.fasterxml.jackson.annotation.JsonValue

enum class DossierDocumentType(@JsonValue val code: String) {
    WORK_CONTRACT("work_contract"),
    RESIDENTIAL_ADDRESS("residential_address"),
    QUESTIONS("questions"),
    CREDIT_CARD_STATEMENT("credit_card_statement"),
    PASSPORT("passport"),
    DRIVING_LICENSE("driving_license"),
    ID_CARD("id_card"),
    KBIS("kbis"),
    CREDIT_CARD("credit_card"),
    INSURANCE_CARD("insurance_card", ),
    CASH_ADVANCE_APPLICATION("cash_advance_application", ),
    CORPORATE_RESOLUTION_CERTIFICATE("corporate_resolution_certificate"),
    LEASE_AGREEMENT("lease_agreement", ),
    LOAN_APPLICATION("loan_application", ),
    MORTGAGE_APPLICATION("mortgage_application", ),
    TAX_RETURN("tax_return", ),
    VEHICLE_TITLE("vehicle_title", ),
    VOIDED_CHECK("voided_check", ),
    STUDENT_CARD("student_card", ),
    HEALTH_CARE_CARD("health_care_card", ),
    COUNCIL_BILL("council_bill", ),
    SENIORS_CARD("seniors_card", ),
    MEDICARE_CARD("medicare_card", ),
    BIRTH_CERTIFICATE("birth_certificate", ),
    US_SOCIAL_SECURITY_CARD("us_social_security_card", ),
    WORKING_WITH_CHILDREN_CHECK("working_with_children_check"),
    SUPERANNUATION_STATEMENT("superannuation_statement"),
    TRADE_ASSOCIATION_CARD("trade_association_card"),
    SCHOOL_ENROLMENT_LETTER("school_enrolment_letter"),
    PHONE_BILL("phone_bill"),
    SOCIAL_SECURITY_CARD("social_security_card"),
    BANK_STATEMENT("bank_statement"),
    UTILITY_BILL("utility_bill"),
    PAY_SLIP("pay_slip"),
    VOTING_LETTER("voting_letter"),
    BELGIAN_LEASE_AGREEMENT("belgian_lease_agreement"),
    RESIDENCE_CARD("residence_card"),
    RESIDENCE_CERTIFICATE("residence_certificate"),
    TAX_ID_CERTIFICATE("tax_id_certificate")
}
